feat():compliance with TF 0.15
robburger/terraform-pr-commenter pull request #10
Opened 2021-04-21 14:46 UTC by ADefossez-Zenika

2021-04-24 19:21 UTC, robburger requested changes
@ADefossez-Zenika mind updating your PR with the suggestion?

2021-04-24 19:21 UTC, robburger commented on entrypoint.sh
> +plan.|No changes. Infrastructure is up-to-date.)$/,$!d') # Strip refresh section
Looks like this is expected to be truncated: https://github.com/hashicorp/terraform/blob/v0.15.0/command/views/operation_test.go#L93
(Also just keeping this as a one-liner.)
```suggestion
    CLEAN_PLAN=$(echo "$INPUT" | sed -r '/^(An execution plan has been generated and is shown below.|Terraform used the selected providers to generate the following execution|No changes. Infrastructure is up-to-date.)$/,$!d') # Strip refresh section
```

2021-04-26 07:09 UTC, ADefossez-Zenika commented
you're right ;)

2021-04-26 10:10 UTC, robburger approved these changes

2021-04-26 10:10 UTC, merged